-common
  multiplier: 1
- BANKNIFTY
  underlying: 'NSE:BANKNIFTY'
  ce: -100
  pe: 100
  expiry: 23OCT
  lotsize: 45
  stoploss: 20
- NIFTY
  underlying: 'NSE:NIFTY 50'
  ce: -200
  pe: 200
  expiry: 23OCT
  lotsize: 25
  stoploss: 10
