credentials:
    username: XXXXX
    password: XXXXX
    time_based_otp_key: XXXXXXXX

symbols:
  - common:
      multiplier: 1
      live: 0 # anything other than 0 is consider live
  - BANKNIFTY:
      underlying: 'NSE:NIFTY BANK'
      ce: -500
      pe: 500
      diff: 100
      expiry: 23OCT
      lotsize: 45
      stoploss: 20
      segment: NFO-OPT
  - NIFTY:
      underlying: 'NSE:NIFTY 50'
      ce: -200
      pe: 200
      diff: 50
      expiry: 23OCT
      lotsize: 25
      stoploss: 10
      segment: NFO-OPT
